default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ "check", "--select", "I", "--fix" ]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.8
    hooks:
    -   id: uv-lock
    -   id: uv-export
        args: ["--frozen", "--no-hashes", "--output-file=requirements.txt"]